export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESSFULL = 'LOGIN_SUCCESSFULL';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED';
export const SIGNUP_SUCCESSFULL = 'SIGNUP_SUCCESSFULL';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const RESET_SIGNUP = 'RESET_SIGNUP';

export const FETCH_USER_LIST_REQUESTED = 'FETCH_USER_LIST_REQUESTED';
export const FETCH_USER_LIST_SUCCESSFULL = 'FETCH_USER_LIST_SUCCESSFULL';
export const FETCH_USER_LIST_FAILURE = 'FETCH_USER_LIST_FAILURE';

export const FETCH_SITES_LIST_REQUESTED = 'FETCH_SITES_LIST_REQUESTED';
export const FETCH_SITES_LIST_SUCCESSFULL = 'FETCH_SITES_LIST_SUCCESSFULL';
export const FETCH_SITES_LIST_FAILURE = 'FETCH_SITES_LIST_FAILURE';

export const UPDATE_PROFILE_REQUESTED = 'UPDATE_PROFILE_REQUESTED';
export const UPDATE_PROFILE_SUCCESSFUL = 'UPDATE_PROFILE_SUCCESSFUL';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const ACTIVATE_USER_REQUESTED = 'ACTIVATE_USER_REQUESTED';
export const ACTIVATE_USER_SUCCESSFUL = 'ACTIVATE_USER_SUCCESSFUL';
export const ACTIVATE_USER_FAILURE = 'ACTIVATE_USER_FAILURE';

export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED';
export const DELETE_USER_SUCCESSFUL = 'DELETE_USER_SUCCESSFUL';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const FETCH_USER_SITES_REQUESTED = 'FETCH_USER_SITES_REQUESTED';
export const FETCH_USER_SITES_SUCCESSFUL = 'FETCH_USER_SITES_SUCCESSFUL';
export const FETCH_USER_SITES_FAILURE = 'FETCH_USER_SITES_FAILURE';

export const FETCH_SITES_BYID_REQUEST = 'FETCH_SITES_BYID_REQUEST';
export const FETCH_SITES_BYID_SUCCESSFUL = 'FETCH_SITES_BYID_SUCCESSFUL';
export const FETCH_SITES_BYID_FAILURE = 'FETCH_SITES_BYID_FAILURE';


export const CHECK_USER_EXIST_REQUEST = 'CHECK_USER_EXIST_REQUEST';
export const CHECK_USER_EXIST_SUCCESSFUL = 'CHECK_USER_EXIST_SUCCESSFUL';
export const CHECK_USER_EXIST_FAILURE = 'CHECK_USER_EXIST_FAILURE';
export const RESET_CHECK_USER_EXIST = 'RESET_CHECK_USER_EXIST';

export const FORGOT_PASSWORD_REQUESST = 'FORGOT_PASSWORD_REQUESST';
export const FORGOT_PASSWORD_SUCCESSFUL = 'FORGOT_PASSWORD_SUCCESSFUL';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const RESET_FORGOT_PASSWORD = 'RESET_FORGOT_PASSWORD';