export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESSFULL = 'LOGIN_SUCCESSFULL';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED';
export const SIGNUP_SUCCESSFULL = 'SIGNUP_SUCCESSFULL';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';