export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESSFULL = 'LOGIN_SUCCESSFULL';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED';
export const SIGNUP_SUCCESSFULL = 'SIGNUP_SUCCESSFULL';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const FETCH_USER_LIST_REQUESTED = 'FETCH_USER_LIST_REQUESTED';
export const FETCH_USER_LIST_SUCCESSFULL = 'FETCH_USER_LIST_SUCCESSFULL';
export const FETCH_USER_LIST_FAILURE = 'FETCH_USER_LIST_FAILURE';

export const FETCH_SITES_LIST_REQUESTED = 'FETCH_SITES_LIST_REQUESTED';
export const FETCH_SITES_LIST_SUCCESSFULL = 'FETCH_SITES_LIST_SUCCESSFULL';
export const FETCH_SITES_LIST_FAILURE = 'FETCH_SITES_LIST_FAILURE';

export const UPDATE_PROFILE_REQUESTED = 'UPDATE_PROFILE_REQUESTED';
export const UPDATE_PROFILE_SUCCESSFUL = 'UPDATE_PROFILE_SUCCESSFUL';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const ACTIVATE_USER_REQUESTED = 'ACTIVATE_USER_REQUESTED';
export const ACTIVATE_USER_SUCCESSFUL = 'ACTIVATE_USER_SUCCESSFUL';
export const ACTIVATE_USER_FAILURE = 'ACTIVATE_USER_FAILURE';